// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
///   name: 'SecondaryApp',
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQAfdUYO3PAgQui6IdOw_WMITcdZcqh4',
    appId: '1:89929941024:web:91ca81f5b5639aa9c23c45',
    messagingSenderId: '89929941024',
    projectId: 'landform-identifier',
    authDomain: 'landform-identifier.firebaseapp.com',
    databaseURL: 'https://acera-landforms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'landform-identifier.appspot.com',
    measurementId: 'G-M33VXBK6GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3pj-QKoegw_49ruIX_T-izVcknOKLTzE',
    appId: '1:395794160388:android:9f5c83c637c811bfcc4e51',
    messagingSenderId: '395794160388',
    projectId: 'acera-landforms',
    databaseURL: 'https://acera-landforms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'acera-landforms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLr0Gw5LTK6__3O5PxmKWp0wsJaCWWMQ',
    appId: '1:89929941024:ios:f375e6e2244f7818c23c45',
    messagingSenderId: '89929941024',
    projectId: 'landform-identifier',
    databaseURL: 'https://acera-landforms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'landform-identifier.appspot.com',
    iosBundleId: 'com.example.landformIdentifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCLr0Gw5LTK6__3O5PxmKWp0wsJaCWWMQ',
    appId: '1:89929941024:ios:f375e6e2244f7818c23c45',
    messagingSenderId: '89929941024',
    projectId: 'landform-identifier',
    databaseURL: 'https://acera-landforms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'landform-identifier.appspot.com',
    iosBundleId: 'com.example.landformIdentifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqQAfdUYO3PAgQui6IdOw_WMITcdZcqh4',
    appId: '1:89929941024:web:caaa5afb3cd1f2b6c23c45',
    messagingSenderId: '89929941024',
    projectId: 'landform-identifier',
    authDomain: 'landform-identifier.firebaseapp.com',
    databaseURL: 'https://acera-landforms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'landform-identifier.appspot.com',
    measurementId: 'G-VKVMP7DB0H',
  );
}