import 'package:landform_identifier/accurate_result.dart';
import 'package:landform_identifier/graph_page.dart';
import 'package:landform_identifier/landform_classes.dart';
import 'package:landform_identifier/landing_page.dart'; // Import LandingPage
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <- generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Landformtifier',
      theme: ThemeData(primarySwatch: Colors.green),
      home: LandingPage(), // Changed from HomePage() to LandingPage()
      routes: {
        '/accurate-result': (context) => AccurateResultPage(),
        '/graph': (context) => GraphPage(),
        '/landform-classes': (context) => LandformClassesPage(),
      },
    );
  }
}